
def build(bld):

    brushlib = bld(
        features='c cshlib',
        uselib='GLIB JSONC',
        source=bld.path.ant_glob('*.c'),
        target='brushlib',
        includes='. ..',
    )

# vim:ft=python
