
def build(bld):

    brushlib_version_h = bld(
        features='subst',
        source = 'brushlib-version.h.in',
        target = 'brushlib-version.h',
        **bld.env['subst_dict']
    )

    brushlib = bld(
        features='c cshlib',
        uselib='GLIB JSONC',
        source=bld.path.ant_glob('*.c'),
        target='brushlib',
        includes='. ..',
    )

# vim:ft=python
